#系统的基础路径
server: t
use_server: 1
mizhu: https://api.mizholdings.com/
#mizhu: http://192.168.3.151:8081/
mizhumanage: https://api.huijudi.cn/
#mizhumanage: http://192.168.3.151:8081/
kaca: https://develop.kacha.xin/
