t: #测试服务器
  teacher: #教师属性
    account: teacher003 #默认账号和密码
    password: 111111
    list: #用于随机
      - account: 18767126032
        password: 111111
  jigou: #机构
    account: tester
    password: 111111
    list:
      - account: tester002
        password: 111111
  admin: #管理员
    account: houhonglin
    password: 111111
    list:
      - account: houhonglin
        password: 111111
  student: #学生
    account: temp002
    password: 111111
    format: #格式化获取
      - name: account
        value: robot%04d
        start: 0
        end: 200
      - name: password
        value: 111111
    list:
      - account: robot0101
        password: 111111
      - account: robot0102
        password: 111111
      - account: robot0103
        password: 111111
  phone: #手机号
    list:
      - 18000000001
      - 18000000002
      - 18000000003
      - 18000000004
      - 18000000005
      - 18000000006
    registered: 16600010000
    unregistered: 16612312312
    format:
      - name: phone
        value: 17%09d
        start: 0
        end: 9
  phonee_account:
    account: 1349348420
    password: 8cheng
  email:
    account: 186201712028@hxlsjzfx
    password: 8cheng
  lisi:
    phone: 13457691177
  merge:
    phone: 16612312100
    password: 111111
    nickname: 合并专用
    account: merge001
    mizhuTime: 30
    mizhuCoin: 0
  temp:
    account: yk28920826
    password: 8cheng
    phone: 18700000202
  teacher_execl:
    - 班级名称: ""
      年级: ""
      教师姓名: 教师001
      任教学科: 语文
      教师手机号: "18000000001"
    - 班级名称: ""
      年级: ""
      教师姓名: 教师002
      任教学科: 语文
      教师手机号: "18000000002"
    - 班级名称: ""
      年级: ""
      教师姓名: 教师003
      任教学科: 语文
      教师手机号: "18000000003"
  student_execl:
    - 姓名: "学生001"
      账号: "baby001"
      密码: "111111"
    - 姓名: "学生002"
      账号: "baby002"
      密码: "111111"
    - 姓名: "学生003"
      账号: "baby003"
      密码: "111111"


p:
  teacher:
    account: teacher004
    password: 111111
    list: #用于随机抽取
      - account: 18767126032
        password: 111111
      - account: vta001
        password: 111111
  jigou:
    account: tester
    password: 111111
    list:
      - account: tester
        password: 111111
  admin:
    account: yangjiaqi
    password: cheng8111
    list:
      - account: yangjiaqi
        password: cheng8111
  phone:
    registered: 16600010000
    unregistered: 16612312312
    list:
      - 18000000001
      - 18000000002
      - 18000000003
      - 18000000004
      - 18000000005
      - 18000000006
    format:
      value: 18%09d
      start: 0
      end: 9
  email:
    account: 2301031055201@dsszxx
    password: 8cheng
  phonee_account:
    account: 1489926104
    password: 111111
  lisi:
    phone: 13457691177
  student:
    account: temp001
    password: 111111
    format:
      value: yangjiaqitest%04d
      start: 0
      end: 200
    list:
      - account: yangjiaqitest0001
        password: 111111
  merge:
    phone: 16612312100
    password: 111111
    nickname: 合并专用
    account: merge001
    mizhuTime: 30
    mizhuCoin: 0
  temp:
    account: yk99111
    password: 8cheng
    phone: 18767126032
